### ISSUE TITLE
**Requires Neo4j experience: Design Database and API updates for city and age filtering on Tripler search

### ISSUE THREAD

**Issue by shauminn-colab** [colab-coop/HelloVoter#44]
As an ambassador, I want to be able to filter the suggested triplers  list I am shown or my tripler search results by city and age.

**Background**: We aren't currently importing city or age when we import Tripler CSVs, so the import script and data model will need to be update to accommodate these additional fields and other additional fields that are unrelated to adding city and age filtering on triplers search
- Current user experience on /triplers/add lists 100 Triplers that are geographically closest to the Ambassador (based on lat/long) - requested from `suggest-triplers` API 
- Ambassador can search for either first or last name
**Reference screenshot**
<img width="1120" alt="Screen Shot 2020-09-25 at 5 22 51 PM" src="https://user-images.githubusercontent.com/71728947/94323628-c7f03c80-ff53-11ea-9eaa-59c36dc8f1d9.png">

**Desired user experience (for reference - not actually part of this ticket :) **:
- Ambassador can filter their default Tripler list from `suggest-triplers` API or their search results according to certain parameters
- Ambassadors should be able to select multiple filters at once in either case
- Filters to add:
**City**: In UI this would be a dropdown list of the top 100 cities that are in the Triplers data
**Age**: In UI this would be a dropdown list of age ranges, e.g. 18-30, 31-40, 41-50, etc.

_The goal of this ticket is to design the API updates to `suggest-triplers` and the triplers search based on the above desired UX and the amounts of data expected in each filter._

**Comment by cooperka** [comment]
### To support filtering by city and age

Backend files to touch:
- CSV import files need to include age
- `server/scripts/importer/import.js#parseRecord` needs to parse age from CSV and save to the DB
    - Note: it seems city is already imported (`city: record[10]`)
- `server/app/routes/api/v1/va/triplers.js#suggestTriplers` is probably fine as-is unless we want to automatically include people of a similar age range? (There's no "search" functionality here)
- `server/app/routes/api/v1/va/triplers.js#searchTriplersAmbassador, #searchTriplersAdmin` need to pass through `req.query.city, age`, stop defaulting to an empty array if name is undefined (and DRY up the two methods)
- `server/app/services/triplers.js#searchTriplersAmbassador, #searchTriplersAdmin` (DRY up the two methods)
- `server/app/services/triplers.js#buildSearchTriplerQuery` needs to recognize `query.city, age` and build into Cypher statement (somewhat fuzzy? e.g. if the person is 31 maybe they should show up in the 18-30 range) and also handle any type of query (e.g. if all fields are blank return empty array here instead of as mentioned above. Currently it throws an error if name is missing)

Frontend files to touch:
- `AddTripler <SearchBarContainer>` will need to display new fields for city, age dropdowns
- `AddTripler#search api.searchTriplers(firstName, lastName)` will need to include city, age and pass as URL params to backend
- `AddTripler#useEffect api.fetchFreeTriplers()` is probably fine as-is since it's not searching

Reference:
- Existing cypher query that filters by name (generated in `server/app/services/triplers.js#searchTriplersAmbassador` by calling `neode ... .build().query` instead of `neode ... .execute()`):

    ```cypher
    MATCH (t:Tripler)
    WHERE (apoc.text.levenshteinDistance("foo", t.first_name) < 3.0
      AND apoc.text.levenshteinDistance("bar", t.last_name) < 3.0
      AND NOT ()-[:CLAIMS]->(t)
      AND NOT ()-[:WAS_ONCE]->(t))
    RETURN t LIMIT 1000
    ```

- Modified to include city and age example:

    ```diff
     MATCH (t:Tripler)
     WHERE (apoc.text.levenshteinDistance("foo", t.first_name) < 3.0
       AND apoc.text.levenshteinDistance("bar", t.last_name) < 3.0
    +  AND t.age >= 18 AND t.age <= 30
    +  AND apoc.convert.fromJsonMap(t.address).city = "Oak Creek"
       AND NOT ()-[:CLAIMS]->(t)
       AND NOT ()-[:WAS_ONCE]->(t))
     RETURN t LIMIT 1000
    ```

If this ends up being a performance issue, we could always denormalize `city` and store it directly on the Tripler node instead of parsing the `address` JSON but I suggest holding off on this unless needed.

### Summary

Overall this is not bad! It basically just requires passing more info around, no significant refactoring needed. Feedback is welcome; anything deeper/functionality I missed?

**Comment by brodavi** [comment]
@cooperka thanks! I think this is a great summary. Would you be willing to give it a try? We will have a stress testing server up and running shortly that we can test it on.

**Comment by cooperka** [comment]
@shauminn-colab have we already considered how this feature will affect user privacy? (I'm not sure where the data is coming from, maybe it's a public voter registry anyway). I could imagine using this feature maliciously to discover what city someone lives in if they have a unique enough name.

I'm implementing it using a map of age ranges, so for example you can query `/search?firstName=foo&ageGroup=b` to get someone named Foo who is 18-30 years old but you cannot modify the URL to narrow the age to something more specific than that.

```js
const ageGroupMap = {
  a: { min: 0, max: 18 },
  b: { min: 18, max: 30 },
  c: { min: 31, max: 40 },
  d: { min: 41, max: 50 },
  e: { min: 51, max: 60 },
  f: { min: 61, max: 200 },
}
```

If this is all public data then perhaps it's overkill and I can just let the URL accept `ageMin=18&ageMax=30`.

**Comment by shauminn-colab** [comment]
yay @cooperka! and thanks for raising that question -- the data is handed to us for importing by BlockPower who in turn purchased datasets from organizations that maintain voter data and contact lists, so the information is not public. We already show city and state as part of the display_address so this wouldn't be adding any additional information that isn't already there -- see this example staging data:
<img width="1114" alt="Screen Shot 2020-10-02 at 1 43 25 PM" src="https://user-images.githubusercontent.com/71728947/94963368-477e8e00-04b5-11eb-8bc9-87c6905135d2.png">

**Comment by cooperka** [comment]
Okay, it sounds like age range grouping is important then! I'll leave it implemented that way 👍
